//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1572, 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace Chess.DataModels
{
	/// <summary>
	/// Database       : KaiJuKu
	/// Data Source    : KaiJuKu
	/// Server Version : 3.24.0
	/// </summary>
	public partial class KaiJuKuDB : LinqToDB.Data.DataConnection
	{
		public ITable<Book>   Books   { get { return this.GetTable<Book>(); } }
		public ITable<Mybook> Mybooks { get { return this.GetTable<Mybook>(); } }

		public KaiJuKuDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public KaiJuKuDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public KaiJuKuDB(LinqToDbConnectionOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public KaiJuKuDB(LinqToDbConnectionOptions<KaiJuKuDB> options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("book")]
	public partial class Book
	{
		[Column("id"), NotNull    ] public long      Id        { get; set; } // integer
		[Column(),        Nullable] public string    Event     { get; set; } // varchar(100)
		[Column(),        Nullable] public DateTime? Date      { get; set; } // date
		[Column(),        Nullable] public string    RedTeam   { get; set; } // varchar(50)
		[Column(),        Nullable] public string    Red       { get; set; } // varchar(20)
		[Column(),        Nullable] public string    BlackTeam { get; set; } // varchar(50)
		[Column(),        Nullable] public string    Black     { get; set; } // varchar(20)
		[Column(),        Nullable] public string    Result    { get; set; } // varchar(30)
		[Column(),        Nullable] public string    ECCO      { get; set; } // varchar(50)
		[Column(),        Nullable] public string    Opening   { get; set; } // varchar(200)
		[Column(),        Nullable] public string    Variation { get; set; } // varchar(50)
	}

	[Table("mybook")]
	public partial class Mybook
	{
		[Column("date"),   Nullable] public DateTime? Date   { get; set; } // date
		[Column("type"),   Nullable] public string    Type   { get; set; } // varchar(50)
		[Column("title"),  Nullable] public string    Title  { get; set; } // varchar(50)
		[Column("author"), Nullable] public string    Author { get; set; } // varchar(50)
		[Column("video"),  Nullable] public string    Video  { get; set; } // varchar(200)
		[Column("memo"),   Nullable] public string    Memo   { get; set; } // text(3000)
		[Column("record"), Nullable] public string    Record { get; set; } // varchar(10000)
	}
}
